'words'[
  ({
    id: 1,
    status: 'new',
    addedAt: '2025-08-07T06:43:43.000Z',
    lastReviewedAt: null,
    nextReviewAt: '2025-08-08T06:43:43.000Z',
    totalReviews: 0,
    correctCount: 0,
    currentStreak: 0,
    easeFactor: '2.5',
    intervalDays: 1,
    personalNote: null,
    isFavorite: false,
    word: 'example',
    definition: 'something that is typical of the group of things that it is a member of:',
    vnDefinition: 'Một cái gì đó là điển hình của nhóm những điều mà nó là một thành viên của:',
    partOfSpeech: 'noun',
    examples: [
      'Could you give me an example of the improvements you have mentioned?',
      'This painting is a marvellous example of her work.',
    ],
    cefrLevel: 'A1',
    ukIpa: 'ɪɡˈzɑːm.pəl',
    usIpa: 'ɪɡˈzæm.pəl',
    ukAudioUrl: 'https://dictionary.cambridge.org/media/english/uk_pron/u/uke/ukexa/ukexami004.mp3',
    usAudioUrl: 'https://dictionary.cambridge.org/media/english/us_pron/e/exa/examp/example.mp3',
    priority: 'high',
    isOverdue: true,
    daysOverdue: 10,
    category: 'new',
  },
  {
    id: 2,
    status: 'new',
    addedAt: '2025-08-07T06:43:49.000Z',
    lastReviewedAt: null,
    nextReviewAt: '2025-08-08T06:43:49.000Z',
    totalReviews: 0,
    correctCount: 0,
    currentStreak: 0,
    easeFactor: '2.5',
    intervalDays: 1,
    personalNote: null,
    isFavorite: false,
    word: 'example',
    definition: 'used when giving an example of the type of thing you mean:',
    vnDefinition: 'được sử dụng khi đưa ra một ví dụ về loại điều bạn có nghĩa là:',
    partOfSpeech: 'noun',
    examples: [
      'Offices can easily become more environmentally friendly by, for example, using recycled paper.',
    ],
    cefrLevel: 'A1',
    ukIpa: 'ɪɡˈzɑːm.pəl',
    usIpa: 'ɪɡˈzæm.pəl',
    ukAudioUrl: 'https://dictionary.cambridge.org/media/english/uk_pron/u/uke/ukexa/ukexami004.mp3',
    usAudioUrl: 'https://dictionary.cambridge.org/media/english/us_pron/e/exa/examp/example.mp3',
    priority: 'high',
    isOverdue: true,
    daysOverdue: 10,
    category: 'new',
  },
  {
    id: 3,
    status: 'new',
    addedAt: '2025-08-07T07:11:36.000Z',
    lastReviewedAt: null,
    nextReviewAt: '2025-08-08T07:11:36.000Z',
    totalReviews: 0,
    correctCount: 0,
    currentStreak: 0,
    easeFactor: '2.5',
    intervalDays: 1,
    personalNote: null,
    isFavorite: false,
    word: 'long',
    definition: 'continuing for a large amount of time:',
    vnDefinition: 'Tiếp tục trong một khoảng thời gian lớn:',
    partOfSpeech: 'adjective',
    examples: [
      'a long film/meeting',
      "I've been waiting a long time.",
      "It's a long time since I worked there.",
    ],
    cefrLevel: 'A1',
    ukIpa: 'lɒŋ',
    usIpa: 'lɑːŋ',
    ukAudioUrl: 'https://dictionary.cambridge.org/media/english/uk_pron/u/ukl/uklon/uklonel004.mp3',
    usAudioUrl: 'https://dictionary.cambridge.org/media/english/us_pron/l/lon/long_/long.mp3',
    priority: 'high',
    isOverdue: true,
    daysOverdue: 10,
    category: 'new',
  },
  {
    id: 4,
    status: 'new',
    addedAt: '2025-08-07T07:11:47.000Z',
    lastReviewedAt: null,
    nextReviewAt: '2025-08-08T07:11:47.000Z',
    totalReviews: 0,
    correctCount: 0,
    currentStreak: 0,
    easeFactor: '2.5',
    intervalDays: 1,
    personalNote: null,
    isFavorite: false,
    word: 'long',
    definition: 'a long period of time before or after something:',
    vnDefinition: 'Một khoảng thời gian dài trước hoặc sau một cái gì đó:',
    partOfSpeech: 'adverb',
    examples: [
      'She left the house long before I arrived.',
      "It wasn't long before he was back with his family.",
      'He did not join them until long after they had eaten.',
    ],
    cefrLevel: 'A2',
    ukIpa: 'lɒŋ',
    usIpa: 'lɑːŋ',
    ukAudioUrl: 'https://dictionary.cambridge.org/media/english/uk_pron/u/ukl/uklon/uklonel004.mp3',
    usAudioUrl: 'https://dictionary.cambridge.org/media/english/us_pron/l/lon/long_/long.mp3',
    priority: 'high',
    isOverdue: true,
    daysOverdue: 10,
    category: 'new',
  },
  {
    id: 5,
    status: 'new',
    addedAt: '2025-08-18T05:58:33.000Z',
    lastReviewedAt: null,
    nextReviewAt: '2025-08-19T05:58:33.000Z',
    totalReviews: 0,
    correctCount: 0,
    currentStreak: 0,
    easeFactor: '2.5',
    intervalDays: 1,
    personalNote: null,
    isFavorite: false,
    word: 'accommodation',
    definition: 'a place to stay or live:',
    vnDefinition: 'một nơi để ở hoặc sống:',
    partOfSpeech: 'noun',
    examples: [
      'They paid for his flights and hotel accommodation.',
      "There's a shortage of cheap accommodation in the city.",
      'There is accommodation for about five hundred students on campus.',
    ],
    cefrLevel: 'B1',
    ukIpa: 'əˌkɒm.əˈdeɪ.ʃən',
    usIpa: 'əˌkɑː.məˈdeɪ.ʃən',
    ukAudioUrl: 'https://dictionary.cambridge.org/media/english/uk_pron/u/uka/ukacc/ukacces013.mp3',
    usAudioUrl:
      'https://dictionary.cambridge.org/media/english/us_pron/c/cal/cald4/cald4us0013.mp3',
    priority: 'low',
    isOverdue: false,
    daysOverdue: 0,
    category: 'new',
  },
  {
    id: 6,
    status: 'new',
    addedAt: '2025-08-18T11:54:02.000Z',
    lastReviewedAt: null,
    nextReviewAt: '2025-08-19T11:54:02.000Z',
    totalReviews: 0,
    correctCount: 0,
    currentStreak: 0,
    easeFactor: '2.5',
    intervalDays: 1,
    personalNote: null,
    isFavorite: false,
    word: 'man',
    definition:
      'an adult who lives and identifies as male though they may have been considered to have a different sex at birth:',
    vnDefinition:
      'Một người trưởng thành sống và xác định là nam giới mặc dù họ có thể được coi là có một tình dục khác khi sinh:',
    partOfSpeech: 'noun',
    examples: [
      'Connor is a man who was assigned female at birth.',
      'Their doctor encouraged them to live as a man for a while before undergoing surgical transition.',
      'Mark is a transgender man (= he was considered to be female at birth).',
    ],
    cefrLevel: 'A1',
    ukIpa: 'mæn',
    usIpa: 'mæn',
    ukAudioUrl: 'https://dictionary.cambridge.org/media/english/uk_pron/u/ukm/ukmam/ukmammo003.mp3',
    usAudioUrl: 'https://dictionary.cambridge.org/media/english/us_pron/e/eus/eus72/eus72888.mp3',
    priority: 'low',
    isOverdue: false,
    daysOverdue: 0,
    category: 'new',
  },
  {
    id: 7,
    status: 'new',
    addedAt: '2025-08-18T12:29:02.000Z',
    lastReviewedAt: null,
    nextReviewAt: '2025-08-19T12:29:02.000Z',
    totalReviews: 0,
    correctCount: 0,
    currentStreak: 0,
    easeFactor: '2.5',
    intervalDays: 1,
    personalNote: null,
    isFavorite: false,
    word: 'woman',
    definition: 'an adult female human being:',
    vnDefinition: 'Một con người nữ trưởng thành:',
    partOfSpeech: 'noun',
    examples: [
      "She's a really nice woman.",
      'A woman and two men were arrested the day after the explosion.',
      'Women first got the vote in Britain in 1918.',
    ],
    cefrLevel: 'A1',
    ukIpa: 'ˈwʊm.ən',
    usIpa: 'ˈwʊm.ən',
    ukAudioUrl: 'https://dictionary.cambridge.org/media/english/uk_pron/u/ukw/ukwit/ukwitte026.mp3',
    usAudioUrl: 'https://dictionary.cambridge.org/media/english/us_pron/w/wom/woman/woman.mp3',
    priority: 'low',
    isOverdue: false,
    daysOverdue: 0,
    category: 'new',
  })
];
